namespace Migue.Domain.Data.SeedData;

internal static class CompetencyQuestionSeedData
{
    public static readonly (string Competency, string Text, string[] Options)[] Questions =
    [
        ("Comunicação", "Quando precisa explicar algo técnico para alguém que não domina o assunto, como você costuma agir?",
            ["Explico usando os termos técnicos que já conheço.", "Procuro adaptar a explicação à pessoa.", "Uso exemplos práticos para facilitar o entendimento.", "Primeiro tento entender o que a pessoa já sabe."]),
        ("Comunicação", "Quando percebe que alguém não entendeu uma explicação sua, o que costuma fazer?",
            ["Explico novamente da mesma maneira.", "Tento explicar de outra forma.", "Uso um exemplo ou situação prática.", "Pergunto qual parte ficou confusa."]),
        ("Comunicação", "Quando discorda de alguém durante uma discussão, como normalmente reage?",
            ["Apresento imediatamente meu ponto de vista.", "Procuro entender o argumento da outra pessoa.", "Apresento dados ou exemplos que sustentem minha opinião.", "Prefiro evitar o confronto e seguir em frente."]),

        ("Resolução de Problemas", "Quando surge um problema que você nunca enfrentou antes, o que costuma fazer primeiro?",
            ["Procuro alguém que já tenha enfrentado algo parecido.", "Pesquiso para entender melhor o problema.", "Começo a testar possíveis soluções.", "Tento identificar primeiro a causa do problema."]),
        ("Resolução de Problemas", "Quando uma solução que você tentou não funciona, como costuma reagir?",
            ["Procuro imediatamente outra alternativa.", "Tento entender por que a solução falhou.", "Peço ajuda para encontrar outro caminho.", "Volto algumas etapas e reavalio o problema."]),
        ("Resolução de Problemas", "Quando recebe um problema aparentemente urgente, qual costuma ser sua primeira reação?",
            ["Começo a agir imediatamente.", "Tento entender o impacto antes de agir.", "Confirmo primeiro se realmente é uma prioridade.", "Divido o problema em partes menores."]),

        ("Organização", "Quando recebe várias tarefas ao mesmo tempo, como costuma organizá-las?",
            ["Começo pela tarefa que chegou primeiro.", "Começo pela que considero mais importante.", "Organizo as tarefas por prioridade e prazo.", "Escolho uma tarefa e vou resolvendo uma por vez."]),
        ("Organização", "Como costuma acompanhar aquilo que precisa fazer?",
            ["Mantenho tudo na memória.", "Faço anotações quando necessário.", "Utilizo listas, ferramentas ou algum sistema de organização.", "Organizo somente as tarefas mais importantes."]),
        ("Organização", "Quando percebe que sua organização inicial não está funcionando, o que faz?",
            ["Continuo seguindo o planejamento original.", "Faço alguns ajustes.", "Reorganizo completamente as prioridades.", "Peço ajuda para definir o que deve ser priorizado."]),

        ("Proatividade", "Você percebe um problema que ainda não está afetando ninguém. O que costuma fazer?",
            ["Espero alguém solicitar alguma ação.", "Aviso quem é responsável.", "Tento resolver antes que o problema aumente.", "Registro a situação para tratar posteriormente."]),
        ("Proatividade", "Quando termina uma tarefa antes do prazo, o que normalmente faz?",
            ["Aguardo a próxima tarefa.", "Procuro algo que possa melhorar.", "Pergunto se existe outra prioridade.", "Aproveito o tempo para descansar ou fazer outra coisa."]),
        ("Proatividade", "Você identifica uma melhoria em um processo que funciona, mas poderia ser melhor. Como costuma agir?",
            ["Faço a mudança imediatamente.", "Apresento a ideia antes de alterar o processo.", "Registro a sugestão para discutir posteriormente.", "Prefiro não alterar algo que já funciona."]),

        ("Adaptabilidade", "Quando uma prioridade muda repentinamente, como você costuma reagir?",
            ["Tenho dificuldade para mudar o planejamento.", "Ajusto o que estava fazendo e continuo.", "Reorganizo rapidamente minhas prioridades.", "Preciso entender primeiro o motivo da mudança."]),
        ("Adaptabilidade", "Quando precisa trabalhar com uma ferramenta nova, como costuma começar?",
            ["Espero alguém me ensinar.", "Procuro documentação ou exemplos.", "Começo a explorar por conta própria.", "Procuro alguém que já conheça a ferramenta."]),
        ("Adaptabilidade", "Quando um plano que você preparou deixa de fazer sentido, o que costuma fazer?",
            ["Tento manter o plano original.", "Faço pequenos ajustes.", "Reformulo o plano completamente.", "Paro para entender melhor o novo cenário."]),

        ("Trabalho em Equipe", "Quando trabalha em uma atividade que depende de outras pessoas, como costuma agir?",
            ["Faço minha parte e aguardo os demais.", "Procuro manter todos alinhados.", "Tento ajudar quando percebo alguma dificuldade.", "Acompanho o andamento das partes que dependem do meu trabalho."]),
        ("Trabalho em Equipe", "Quando percebe que alguém da equipe está com dificuldade, o que costuma fazer?",
            ["Espero que a pessoa peça ajuda.", "Pergunto se ela precisa de ajuda.", "Tento ajudar diretamente.", "Aviso alguém que possa apoiar a situação."]),
        ("Trabalho em Equipe", "Quando sua opinião é diferente da maioria da equipe, como costuma agir?",
            ["Defendo minha opinião até o fim.", "Apresento meus argumentos e escuto os demais.", "Aceito a decisão da maioria.", "Procuro uma alternativa que contemple os diferentes pontos de vista."]),

        ("Pensamento Crítico", "Quando recebe uma informação importante, como costuma avaliá-la?",
            ["Considero a informação recebida como verdadeira.", "Procuro entender a origem da informação.", "Comparo com outras fontes.", "Analiso os dados antes de tirar uma conclusão."]),
        ("Pensamento Crítico", "Quando uma solução parece funcionar muito bem, o que costuma fazer?",
            ["Implemento e sigo em frente.", "Tento entender por que funciona.", "Procuro possíveis limitações.", "Comparo com outras alternativas."]),
        ("Pensamento Crítico", "Quando alguém apresenta uma opinião diferente da sua, como costuma reagir?",
            ["Procuro defender meu ponto de vista.", "Tento entender os argumentos apresentados.", "Procuro evidências que sustentem cada posição.", "Reavalio minha opinião quando encontro novos dados."]),

        ("Gestão de Tempo", "Quando possui várias tarefas com prazos diferentes, como costuma decidir o que fazer primeiro?",
            ["Começo pela tarefa mais rápida.", "Começo pela tarefa com prazo mais próximo.", "Considero prazo, impacto e esforço.", "Começo pela tarefa que considero mais importante."]),
        ("Gestão de Tempo", "Quando percebe que não conseguirá cumprir um prazo, o que costuma fazer?",
            ["Tento trabalhar mais rápido.", "Aviso assim que percebo o risco.", "Reavalio as prioridades.", "Procuro negociar o prazo ou o escopo."]),
        ("Gestão de Tempo", "Quando possui um período livre durante o trabalho, como costuma utilizá-lo?",
            ["Começo alguma tarefa pendente.", "Organizo minhas próximas atividades.", "Procuro melhorias ou aprendizados.", "Aproveito para descansar antes da próxima demanda."]),

        ("Responsabilidade", "Quando comete um erro que afeta uma atividade, como costuma agir?",
            ["Tento corrigir antes de comunicar.", "Comunico o problema e procuro corrigir.", "Analiso primeiro o impacto do erro.", "Procuro entender como evitar que aconteça novamente."]),
        ("Responsabilidade", "Quando assume uma tarefa, o que normalmente considera como sua responsabilidade?",
            ["Entregar aquilo que foi solicitado.", "Garantir que a tarefa seja concluída corretamente.", "Comunicar problemas durante o processo.", "Acompanhar o resultado até o final."]),
        ("Responsabilidade", "Quando percebe que não conseguirá cumprir um compromisso assumido, como reage?",
            ["Tento resolver sozinho.", "Comunico a situação.", "Procuro uma alternativa.", "Reavalio o compromisso e proponho uma nova solução."]),

        ("Aprendizado", "Quando precisa aprender algo novo para realizar uma tarefa, como costuma fazer?",
            ["Procuro um exemplo pronto.", "Pesquiso documentação e materiais.", "Pergunto para alguém que conhece o assunto.", "Tento aprender fazendo."]),
        ("Aprendizado", "Depois de cometer um erro, o que normalmente faz?",
            ["Corrijo e sigo em frente.", "Tento entender o que causou o erro.", "Procuro aprender com a situação.", "Registro o que aconteceu para evitar repetição."]),
        ("Aprendizado", "Quando aprende uma maneira melhor de realizar uma tarefa, o que costuma fazer?",
            ["Passo a utilizá-la.", "Comparo com a forma anterior.", "Compartilho o conhecimento com outras pessoas.", "Procuro aplicar o aprendizado em outras situações."]),

        ("Abertura a Feedback", "Quando recebe um feedback sobre algo que poderia melhorar, como costuma reagir?",
            ["Procuro entender exatamente o que aconteceu.", "Penso sobre o feedback antes de responder.", "Pergunto como poderia melhorar.", "Tenho dificuldade em aceitar críticas inicialmente."]),
        ("Abertura a Feedback", "Quando recebe um feedback com o qual não concorda, o que costuma fazer?",
            ["Explico imediatamente meu ponto de vista.", "Procuro entender os motivos do feedback.", "Peço exemplos concretos.", "Reavalio minha posição depois da conversa."]),
        ("Abertura a Feedback", "Quando alguém elogia seu trabalho, como costuma reagir?",
            ["Agradeço e sigo normalmente.", "Procuro entender o que funcionou bem.", "Tento repetir o comportamento em outras situações.", "Compartilho o reconhecimento com quem participou."]),

        ("Inteligência Emocional", "Quando está sob pressão, como costuma perceber seu próprio comportamento?",
            ["Continuo trabalhando normalmente.", "Percebo que fico mais impaciente.", "Procuro fazer uma pausa ou reorganizar a situação.", "Tento entender o que está causando a pressão."]),
        ("Inteligência Emocional", "Quando alguém reage de maneira agressiva durante uma conversa, como costuma agir?",
            ["Respondo diretamente.", "Tento manter a calma.", "Procuro entender o motivo da reação.", "Encerro a conversa e retomo posteriormente."]),
        ("Inteligência Emocional", "Quando percebe que está frustrado com uma situação, o que costuma fazer?",
            ["Continuo trabalhando normalmente.", "Procuro conversar com alguém.", "Tento entender a causa da frustração.", "Faço uma pausa antes de continuar."]),

        ("Tomada de Decisão", "Quando precisa tomar uma decisão importante, o que costuma considerar?",
            ["Minha experiência.", "Dados disponíveis.", "Opiniões de outras pessoas.", "Impacto e possíveis consequências."]),
        ("Tomada de Decisão", "Quando não possui todas as informações necessárias para decidir, o que costuma fazer?",
            ["Aguardo ter todas as informações.", "Tomo a decisão com o que tenho disponível.", "Procuro informações adicionais.", "Consulto alguém antes de decidir."]),
        ("Tomada de Decisão", "Quando percebe que tomou uma decisão errada, como costuma agir?",
            ["Tento corrigir rapidamente.", "Analiso o que levou à decisão.", "Comunico o problema.", "Procuro evitar que a situação se repita."]),

        ("Criatividade", "Quando precisa resolver algo para o qual não existe um procedimento definido, como costuma agir?",
            ["Procuro adaptar alguma solução existente.", "Crio uma solução nova.", "Procuro referências em outras situações.", "Peço sugestões para outras pessoas."]),
        ("Criatividade", "Quando recebe uma tarefa que poderia ser feita de várias maneiras, como escolhe?",
            ["Utilizo a maneira que já conheço.", "Procuro a maneira mais rápida.", "Comparo diferentes possibilidades.", "Tento encontrar uma abordagem diferente."]),
        ("Criatividade", "Quando identifica uma oportunidade de fazer algo de uma maneira diferente, o que costuma fazer?",
            ["Testo a ideia.", "Converso com alguém antes.", "Comparo com a maneira atual.", "Deixo para outro momento."]),

        ("Colaboração", "Quando precisa realizar uma tarefa que envolve conhecimento de outra pessoa, como costuma agir?",
            ["Tento resolver sozinho primeiro.", "Peço ajuda diretamente.", "Procuro aprender com a pessoa.", "Divido a tarefa com ela."]),
        ("Colaboração", "Quando possui conhecimento que pode ajudar outra pessoa, o que costuma fazer?",
            ["Espero que ela pergunte.", "Ofereço ajuda.", "Compartilho o conhecimento espontaneamente.", "Procuro criar um material para facilitar."]),
        ("Colaboração", "Quando uma atividade depende da contribuição de várias pessoas, como costuma participar?",
            ["Faço minha parte.", "Procuro manter os envolvidos informados.", "Ajudo a organizar o trabalho.", "Procuro identificar possíveis problemas antecipadamente."]),

        ("Liderança", "Quando percebe que uma equipe está sem direção clara, o que costuma fazer?",
            ["Aguardo alguém assumir a liderança.", "Procuro entender o que precisa ser feito.", "Tomo a iniciativa de organizar as próximas ações.", "Sugiro que definam responsabilidades."]),
        ("Liderança", "Quando precisa coordenar uma atividade com outras pessoas, como costuma agir?",
            ["Distribuo as tarefas.", "Alinho objetivos e responsabilidades.", "Acompanho o andamento.", "Procuro apoiar quem estiver com dificuldades."]),
        ("Liderança", "Quando uma decisão da equipe não produz o resultado esperado, como costuma agir?",
            ["Procuro identificar o que deu errado.", "Converso com os envolvidos.", "Busco uma nova abordagem.", "Reavalio as responsabilidades e o processo."]),

        ("Negociação", "Quando precisa chegar a um acordo com alguém que possui uma opinião diferente, o que costuma fazer?",
            ["Defendo minha posição.", "Procuro entender o que a outra pessoa precisa.", "Busco um meio-termo.", "Procuro dados que ajudem na decisão."]),
        ("Negociação", "Quando uma pessoa solicita algo que você não consegue entregar, como costuma responder?",
            ["Explico que não é possível.", "Tento negociar prazo ou escopo.", "Procuro uma alternativa.", "Pergunto qual é a necessidade principal."]),
        ("Negociação", "Quando precisa priorizar entre demandas conflitantes, como costuma agir?",
            ["Escolho a que considero mais importante.", "Procuro alinhar as prioridades com os envolvidos.", "Avalio impacto e urgência.", "Tento encontrar uma solução que atenda parcialmente às demandas."]),

        ("Empatia", "Quando percebe que alguém está tendo dificuldade, como costuma agir?",
            ["Espero que a pessoa peça ajuda.", "Pergunto se está tudo bem.", "Tento entender o que ela está enfrentando.", "Ofereço ajuda diretamente."]),
        ("Empatia", "Quando alguém apresenta uma opinião que você considera equivocada, como costuma responder?",
            ["Explico por que discordo.", "Procuro entender o ponto de vista primeiro.", "Apresento outra perspectiva.", "Pergunto quais fatores levaram àquela opinião."]),
        ("Empatia", "Quando uma pessoa reage de maneira diferente do que você esperava, o que costuma fazer?",
            ["Tento entender o comportamento.", "Pergunto diretamente o que aconteceu.", "Continuo normalmente.", "Reavalio minha própria abordagem."]),

        ("Foco em Resultados", "Quando recebe uma tarefa, como costuma definir se ela foi bem executada?",
            ["Quando termino o que foi solicitado.", "Quando entrego dentro do prazo.", "Quando o resultado atende à necessidade.", "Quando consigo melhorar o resultado esperado."]),
        ("Foco em Resultados", "Quando percebe que uma tarefa está consumindo mais tempo do que deveria, o que costuma fazer?",
            ["Continuo até terminar.", "Procuro uma maneira mais eficiente.", "Reavalio se a tarefa realmente precisa ser feita daquela maneira.", "Peço ajuda."]),
        ("Foco em Resultados", "Quando precisa escolher entre entregar rapidamente e entregar com mais qualidade, como costuma decidir?",
            ["Priorizo a velocidade.", "Priorizo a qualidade.", "Avalio o impacto de cada opção.", "Procuro equilibrar os dois fatores."]),

        ("Planejamento", "Quando começa um projeto novo, qual costuma ser sua primeira preocupação?",
            ["Entender o objetivo.", "Listar as tarefas.", "Definir prazos.", "Identificar riscos e dependências."]),
        ("Planejamento", "Quando possui uma tarefa grande e complexa, como costuma começar?",
            ["Começo pela primeira parte que consigo executar.", "Divido a tarefa em etapas.", "Procuro entender todo o cenário primeiro.", "Converso com outras pessoas envolvidas."]),
        ("Planejamento", "Quando percebe que um planejamento está atrasado, o que costuma fazer?",
            ["Continuo seguindo o planejamento.", "Reorganizo os prazos.", "Reavalio as prioridades.", "Procuro identificar a causa do atraso antes de alterar o plano."]),

        ("Resiliência", "Quando uma tentativa sua não produz o resultado esperado, como costuma reagir?",
            ["Tento novamente.", "Procuro entender o que deu errado.", "Procuro outra abordagem.", "Peço ajuda para encontrar uma alternativa."]),
        ("Resiliência", "Quando recebe várias demandas difíceis ao mesmo tempo, como costuma lidar?",
            ["Resolvo uma por uma.", "Priorizo as mais importantes.", "Procuro ajuda para reorganizar as demandas.", "Tento dividir os problemas em partes menores."]),
        ("Resiliência", "Quando passa por uma situação profissional frustrante, o que costuma fazer depois?",
            ["Sigo normalmente.", "Procuro entender o que aconteceu.", "Converso com alguém sobre a situação.", "Penso no que poderia fazer diferente no futuro."]),

        ("Autonomia", "Quando recebe uma tarefa com poucas instruções, como costuma começar?",
            ["Procuro mais informações.", "Tento definir sozinho o que precisa ser feito.", "Pergunto quais são as expectativas.", "Procuro referências de trabalhos anteriores."]),
        ("Autonomia", "Quando encontra uma dificuldade durante uma tarefa, o que costuma fazer antes de pedir ajuda?",
            ["Tento resolver sozinho.", "Pesquiso possíveis soluções.", "Tento algumas alternativas.", "Pergunto rapidamente para evitar perder tempo."]),
        ("Autonomia", "Quando recebe liberdade para decidir como realizar uma tarefa, como costuma agir?",
            ["Sigo uma forma que já conheço.", "Escolho a abordagem que considero mais eficiente.", "Comparo diferentes possibilidades.", "Procuro validar a abordagem antes de começar."]),

        ("Atenção aos Detalhes", "Quando termina uma tarefa importante, o que costuma fazer antes de entregá-la?",
            ["Entrego assim que termino.", "Faço uma revisão rápida.", "Confiro os principais pontos.", "Faço uma revisão detalhada."]),
        ("Atenção aos Detalhes", "Quando encontra uma pequena inconsistência em um trabalho, como costuma agir?",
            ["Corrijo imediatamente.", "Verifico se ela realmente causa impacto.", "Registro para corrigir posteriormente.", "Procuro entender por que aconteceu."]),
        ("Atenção aos Detalhes", "Quando trabalha com informações importantes, como costuma evitar erros?",
            ["Confio na minha atenção.", "Faço revisões.", "Utilizo listas ou validações.", "Peço que outra pessoa confira quando necessário."]),

        ("Evolução Contínua", "Quando percebe que existe uma maneira melhor de realizar uma atividade que você já domina, o que costuma fazer?",
            ["Continuo usando a maneira atual.", "Experimento a nova abordagem.", "Comparo os resultados.", "Procuro entender se a mudança realmente vale a pena."]),
        ("Evolução Contínua", "Quando olha para um trabalho realizado anteriormente, o que costuma procurar?",
            ["Se o resultado foi alcançado.", "O que poderia ter sido feito melhor.", "O que aprendi com a experiência.", "O que poderia fazer diferente hoje."]),
        ("Evolução Contínua", "Quando percebe uma evolução em determinada habilidade sua, o que costuma fazer?",
            ["Continuo utilizando essa habilidade.", "Procuro novos desafios para desenvolvê-la.", "Compartilho o que aprendi.", "Tento aplicar a habilidade em situações diferentes."]),
    ];
}
