// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migue.Domain.Data;

#nullable disable

namespace Migue.Domain.Data.Migrations
{
    [DbContext(typeof(MigueDbContext))]
    [Migration("20260923201906_AddActivityScoreReasons")]
    partial class AddActivityScoreReasons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Migue.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelfScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelfScoreComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("Migue.Domain.Entities.ActivityScoreReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScoreReasonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.HasIndex("ScoreReasonId");

                    b.HasIndex("ActivityId", "ScoreReasonId")
                        .IsUnique();

                    b.ToTable("ActivityScoreReason");
                });

            modelBuilder.Entity("Migue.Domain.Entities.Competency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.ToTable("Competency");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("CompetencyAssessment");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.ToTable("CompetencyQuestion");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyQuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompetencyQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Signal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyQuestionId");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.ToTable("CompetencyQuestionOption");
                });

            modelBuilder.Entity("Migue.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Migue.Domain.Entities.ScoreReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresComment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sentiment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.ToTable("ScoreReason");
                });

            modelBuilder.Entity("Migue.Domain.Entities.SoftSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.ToTable("SoftSkill");
                });

            modelBuilder.Entity("Migue.Domain.Entities.SoftSkillOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SoftSkillId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.HasIndex("SoftSkillId");

                    b.ToTable("SoftSkillOption");
                });

            modelBuilder.Entity("Migue.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Migue.Domain.Entities.UserCompetencyAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangeCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompetencyAssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetencyQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetencyQuestionOptionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyQuestionId");

                    b.HasIndex("CompetencyQuestionOptionId");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("CompetencyAssessmentId", "CompetencyQuestionId")
                        .IsUnique();

                    b.ToTable("UserCompetencyAnswer");
                });

            modelBuilder.Entity("Migue.Domain.Entities.UserSoftSkillAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SoftSkillId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SoftSkillOptionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId")
                        .IsUnique();

                    b.HasIndex("SoftSkillId");

                    b.HasIndex("SoftSkillOptionId");

                    b.HasIndex("UserId", "SoftSkillId", "CreatedAt");

                    b.ToTable("UserSoftSkillAnswer");
                });

            modelBuilder.Entity("Migue.Domain.Entities.Activity", b =>
                {
                    b.HasOne("Migue.Domain.Entities.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Migue.Domain.Entities.ActivityScoreReason", b =>
                {
                    b.HasOne("Migue.Domain.Entities.Activity", "Activity")
                        .WithMany("ScoreReasons")
                        .HasForeignKey("ActivityId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Migue.Domain.Entities.ScoreReason", "ScoreReason")
                        .WithMany("Activities")
                        .HasForeignKey("ScoreReasonId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("ScoreReason");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyAssessment", b =>
                {
                    b.HasOne("Migue.Domain.Entities.User", "User")
                        .WithMany("CompetencyAssessments")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyQuestion", b =>
                {
                    b.HasOne("Migue.Domain.Entities.Competency", "Competency")
                        .WithMany("Questions")
                        .HasForeignKey("CompetencyId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyQuestionOption", b =>
                {
                    b.HasOne("Migue.Domain.Entities.CompetencyQuestion", "CompetencyQuestion")
                        .WithMany("Options")
                        .HasForeignKey("CompetencyQuestionId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetencyQuestion");
                });

            modelBuilder.Entity("Migue.Domain.Entities.SoftSkillOption", b =>
                {
                    b.HasOne("Migue.Domain.Entities.SoftSkill", "SoftSkill")
                        .WithMany("Options")
                        .HasForeignKey("SoftSkillId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SoftSkill");
                });

            modelBuilder.Entity("Migue.Domain.Entities.UserCompetencyAnswer", b =>
                {
                    b.HasOne("Migue.Domain.Entities.CompetencyAssessment", "CompetencyAssessment")
                        .WithMany("Answers")
                        .HasForeignKey("CompetencyAssessmentId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Migue.Domain.Entities.CompetencyQuestion", "CompetencyQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("CompetencyQuestionId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Migue.Domain.Entities.CompetencyQuestionOption", "CompetencyQuestionOption")
                        .WithMany("Answers")
                        .HasForeignKey("CompetencyQuestionOptionId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Migue.Domain.Entities.User", "User")
                        .WithMany("CompetencyAnswers")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetencyAssessment");

                    b.Navigation("CompetencyQuestion");

                    b.Navigation("CompetencyQuestionOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Migue.Domain.Entities.UserSoftSkillAnswer", b =>
                {
                    b.HasOne("Migue.Domain.Entities.SoftSkill", "SoftSkill")
                        .WithMany("Answers")
                        .HasForeignKey("SoftSkillId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Migue.Domain.Entities.SoftSkillOption", "SoftSkillOption")
                        .WithMany("Answers")
                        .HasForeignKey("SoftSkillOptionId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Migue.Domain.Entities.User", "User")
                        .WithMany("SoftSkillAnswers")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SoftSkill");

                    b.Navigation("SoftSkillOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Migue.Domain.Entities.Activity", b =>
                {
                    b.Navigation("ScoreReasons");
                });

            modelBuilder.Entity("Migue.Domain.Entities.Competency", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyAssessment", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Migue.Domain.Entities.CompetencyQuestionOption", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Migue.Domain.Entities.Project", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Migue.Domain.Entities.ScoreReason", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Migue.Domain.Entities.SoftSkill", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Migue.Domain.Entities.SoftSkillOption", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Migue.Domain.Entities.User", b =>
                {
                    b.Navigation("CompetencyAnswers");

                    b.Navigation("CompetencyAssessments");

                    b.Navigation("SoftSkillAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
